# https://embarkstudios.github.io/cargo-deny/index.html

[graph]
all-features = true
no-default-features = false
targets = [
  { triple = "aarch64-apple-darwin" },
  { triple = "aarch64-apple-ios" },
  { triple = "aarch64-linux-android" },
  { triple = "aarch64-unknown-linux-gnu" },
  { triple = "wasm32-unknown-unknown" },
  { triple = "wasm32-wasi" },
  { triple = "x86_64-apple-darwin" },
  { triple = "x86_64-pc-windows-msvc" },
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "x86_64-unknown-linux-musl" },
]

[output]
feature-depth = 1

[advisories]
db-path      = "~/.cargo/advisory-db"
db-urls      = ["https://github.com/rustsec/advisory-db"]
ignore       = []
unmaintained = "workspace"
yanked       = "deny"

[licenses]
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-2-Clause-Patent",
  "BSD-3-Clause",
  "CC-BY-1.0",
  "CC-BY-2.0",
  "CC-BY-3.0",
  "CC-BY-4.0",
  "CC0-1.0",
  "CDLA-Permissive-1.0",
  "CDLA-Permissive-2.0",
  "FTL",
  "ISC",
  "JSON",
  "MIT",
  "MS-PL",
  "OpenSSL",
  "PostgreSQL",
  "SHL-0.5",
  "SHL-0.51",
  "TCP-wrappers",
  "UPL-1.0",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "W3C-20150513",
  "WTFPL",
  "Xnet",
  "Zlib",
]
confidence-threshold = 0.8
unused-allowed-license = "allow"

[licenses.private]
ignore     = false
registries = []

[bans]
allow-wildcard-paths = true
highlight            = "all"
multiple-versions    = "warn"
wildcards            = "deny"

[bans.workspace-dependencies]
duplicates = 'deny'
unused     = 'deny'

[sources]
allow-git        = []
unknown-git      = "deny"
unknown-registry = "deny"

[sources.allow-org]
bitbucket = []
github    = ["0xMiden"]
gitlab    = []
