name: Web-Client Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'crates/web-client/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'crates/web-client/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'crates/web-client/package-lock.json'
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
    
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      env:
        WASMPACK_INSTALL_DIR: ${{ github.workspace }}/.wasm-pack
    
    - name: Add wasm-pack to PATH
      run: echo "${{ github.workspace }}/.wasm-pack" >> $GITHUB_PATH
    
    - name: Install dependencies
      working-directory: crates/web-client
      run: npm ci
    
    - name: Run tests
      working-directory: crates/web-client
      run: npm test
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: crates/web-client/dist/
