[package]
authors.workspace      = true
description            = "Miden Private Transport Node"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["messaging", "miden"]
license.workspace      = true
name                   = "miden-private-transport-node-bin"
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]

[dependencies]
clap                         = { workspace = true }
miden-private-transport-node = { workspace = true }
tokio                        = { workspace = true }
tracing                      = { workspace = true }
