[package]
authors.workspace      = true
description            = "Miden Private Transport Client CLI"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["messaging", "miden"]
license.workspace      = true
name                   = "miden-private-transport-cli"
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]

[dependencies]
base64                  = { workspace = true }
clap                    = { workspace = true }
miden-objects           = { workspace = true }
miden-private-transport = { workspace = true }
tokio                   = { workspace = true }
tracing                 = { workspace = true }
