[package]
authors.workspace      = true
description            = "Miden Private Transport Client CLI"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["messaging", "miden"]
license.workspace      = true
name                   = "miden-private-transport-cli"
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]

[dependencies]
anyhow                         = { workspace = true }
clap                           = { workspace = true }
futures                        = { workspace = true }
hex                            = { workspace = true }
miden-objects                  = { workspace = true }
miden-private-transport-client = { features = ["sqlite", "tonic"], workspace = true }
tokio                          = { workspace = true }
tracing                        = { workspace = true }
