[book]
authors      = ["Miden contributors"]
description  = "Manual for the Miden Transport Layer node software which is responsible for exchanging private notes in the Miden ecosystem."
language     = "en"
multilingual = false
title        = "The Miden Transport Layer Node Operator and Developer Guide"

[output.html]
git-repository-url = "https://github.com/0xMiden/miden-private-transport"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
